services:
  - type: web
    name: balbers-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ./backend/build.sh
    envVars:
      - key: SERVICE_TYPE
        value: web
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: balbers-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/v3/ping
    autoDeploy: true

  - type: web
    name: balbers-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: https://balbers-backend.onrender.com

databases:
  - name: balbers-db
    plan: free
    databaseName: balbers
    user: balbers
