services:
  - type: web
    name: balbers-backend
    runtime: python
    buildCommand: "cd backend && ./build.sh"
    startCommand: "PYTHONPATH=./backend gunicorn --worker-tmp-dir /dev/shm app:app"
    envVars:
      - key: DATABASE_URL
        value: postgresql://balbers:Ve9BUEk8yqiZEBOrUXzJFqcrlSoGL5ol@dpg-cvngaq7diees73busi20-a/balbers_i8o8
          
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
    healthCheckPath: /api/v3/ping

  - type: web
    name: balbers-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: https://balbers-backend.onrender.com

databases:
  - name: balbers-db
    plan: free
    databaseName: balbers
    user: balbers
  
